---

// Spawn coordinates X, Y, Z
The Spawn: 0,0,0
// Coordinates arenas for player X, Y, Z
1: 0,0,0
// 1 and 2 point arena, for its cleaning. (A cuboid)
1aX: 0
1aY: 0
1aZ: 0
1bX: 0
1bY: 0
1bZ: 0
// Coordinates arenas for player X, Y, Z
2: 0,0,0
// 1 and 2 point arena, for its cleaning. (A cuboid)
2aX: 0
2aY: 0
2aZ: 0
2bX: 0
2bY: 0
2bZ: 0
// Coordinates arenas for the third player X, Y, Z
3: 0,0,0
// 1 and 2 point arena, for its cleaning. (A cuboid)
3aX: 0
3aY: 0
3AZ: 0
3bX: 0
3bY: 0
3bZ: 0
// Coordinates arenas for the fourth player X, Y, Z
4: 0,0,0
// 1 and 2 point arena, for its cleaning. (A cuboid)
4aX: 0
4aY: 0
4aZ: 0
4bX: 0
4bY: 0
4bZ: 0
// Coordinates for the fifth scene Player X, Y, Z
5: 0,0,0
// 1 and 2 point arena, for its cleaning. (A cuboid)
5aX: 0
5aY: 0
5aZ: 0
5bX: 0
5bY: 0
5bZ: 0
